### ISSUE TITLE
Switch placehold.it to local images?

### ISSUE THREAD

**Issue by petecooper** [philwareham/textpattern-hive-admin-theme#243] opened 2018-09-07 14:01 UTC
Couple of placehold.it references that could be brought in-house (and the CSP tightened up further):

https://placehold.it/160/fabc2b/333333
https://placehold.it/128/fabc2b/333333

**Comment by philwareham** [comment] 2018-09-07 14:12
OK, I"ll do that shortly. Good way to test the automation is working!

**Comment by philwareham** [comment] 2018-09-07 14:33
OK, I've amended the current repo. Obviously the 4.6 design patterns are still as-is. I will manually amend those once you've confirmed it works here.

**Comment by petecooper** [comment] 2018-09-07 14:36
4.6 and 4.7 subdomains are live and automation is setup, so we'll know if this all works in about 9 minutes.

**Comment by philwareham** [comment] 2018-09-07 14:38
So 4.6 automation comes from `4.6.x` branch, 4.7 automation comes from (currently) master branch (until I fork off `4.7.x` when we introduce something that is 4.8 dev only)?

**Comment by petecooper** [comment] 2018-09-07 14:41
Correct. See https://github.com/textpattern/server-config/blob/master/servers/files/tractor.textpattern.com/var/www/vhosts/textpattern.com/design-patterns-4-6/staging/build.sh#L6 and https://github.com/textpattern/server-config/blob/master/servers/files/tractor.textpattern.com/var/www/vhosts/textpattern.com/design-patterns-4-7/staging/build.sh#L6

**Comment by philwareham** [comment] 2018-09-07 14:47
Lovely stuff 😀

**Comment by philwareham** [comment] 2018-09-07 14:48
We can probably comfortably build every hour though if that lessens bandwidth and load?

**Comment by petecooper** [comment] 2018-09-07 14:48
Automation working - local images served, close this issue when you're happy @philwareham (dunno if you have additional stuff to do)

![screen shot 2018-09-07 at 15 48 17](https://user-images.githubusercontent.com/226578/45225895-7f567f80-b2b5-11e8-8ac1-b19f9695d2c6.png)

**Comment by philwareham** [comment] 2018-09-07 14:49
Just need to amend the 4.6 branch. And then do the same updates in the classic theme.

**Comment by petecooper** [comment] 2018-09-07 14:51
15 minutes interval is for testing, I'm happy with on the hour. Negligible load with 3x sites automated, expect a bit more with 7x sites automated (classic, etc):

![screen shot 2018-09-07 at 15 49 35](https://user-images.githubusercontent.com/226578/45226043-d0667380-b2b5-11e8-9021-a6d35d16843f.png)

The blue and yellow peaks at 15:45:00 are the build tasks, each site is on a 5 second delay from the last.

**Comment by philwareham** [comment] 2018-09-07 14:53
Well, even once a day is fine. I don't update the themes that frequently and when I do I test locally so these live files are purely for others to reference.

**Comment by petecooper** [comment] 2018-09-07 14:55
Let's start with hourly and dial it back - it's useful to see it working as a feedback mechanism and any problems can be spotted 'n fixed sooner.

**Comment by philwareham** [comment] 2018-09-07 15:04
I'm getting a error 500 on a couple of the images (others are all working as intended). See this page: https://design-patterns.textpattern.com/mockups/secondary/content-image_edit.html

You getting the same error?

**Comment by philwareham** [comment] 2018-09-07 15:05
Oh, scratch that - my HTML is wrong - will fix.

**Comment by petecooper** [comment] 2018-09-07 15:06
`/mockups/mockups` perhaps?

**Comment by philwareham** [comment] 2018-09-07 15:26
This is all done now. Closing - thanks as ever Pete!

**Closed by philwareham** 2018-09-07 15:26 UTC
